// *********** First SMA Strategy: https://academy.moralis.io/lessons/building-a-simple-strategy  ************************************** //

// Try version 3? 
//@version=5 

// strategy(title="50 and 20 SMA Crossing", overlay=true, initial_capital = 2000)
// strategy(title="50 and 20 SMA Crossing", overlay=true, initial_capital = 2000, commission_type="strategy.commission.percent", commission_value=0.2)
strategy(title="50 and 20 SMA Crossing", overlay=true, initial_capital = 2000, commission_type=strategy.commission.percent, commission_value=0.2)



//DEFINITIONS ( V3 `sma()`, `V5 ta.sma()` )
shortMa = ta.sma(close, 20)
longMa = ta.sma(close, 50)

//Connect RSI indicator (3:15): https://academy.moralis.io/lessons/future-inspiration
    //price? closing price. How many bars (hours/days/etc) 14 - standard level:
r = ta.rsi(close, 14)

//Date Range added in: https://academy.moralis.io/lessons/back-testing-part-1-enabling-datasets-selection
// V3 only had input() function:
// fromMonth = input(defval=1, title = "From month", minval=1)
// fromDay = input(defval=1, title = "From day", minval=1)
// fromYear = input(defval=2023, title = "From year", minval=2014) 

// V5 has a input.timeframe() function: https://www.tradingview.com/pine-script-reference/v5/#fun_input.timeframe
// indicator("input.timeframe", overlay=true)
// i_res = input.timeframe('D', "Custom Timeframe", options=['D', 'W', 'M', 'Y'], tooltip = "edit marone!")
// fromMonth = input(defval=1, title="From Month", minval=1)
fromMonth = input.int(defval=1, title="Start Month", minval=1, tooltip = "Select the Month")
fromDay = input.int(defval=1, title="Start Day", minval=1, tooltip = "Select the Day")
fromYear = input.int(defval=2023, title="Start Month", minval=2014, tooltip = "Select the Year")

// toMonth = input(defval=1, title = "To month", minval=1)
// toDay = input(defval=1, title = "To day", minval=1)
// toYear = input(defval=2023, title = "To year", minval=2014) 

toMonth = input.int(defval=12, title="End Month", minval=1, tooltip = "Select the Month")
toDay = input.int(defval=31, title="End Day", minval=1, tooltip = "Select the Day")
toYear = input.int(defval=2023, title="End Month", minval=2014, tooltip = "Select the Year")

//Get Amount to trade 
trade_amount = input.float(defval=0.1, title="Amount to Trade", tooltip="Enter Amount to Trade")



// **************************   LOGIC   ************************************************************************ //

    //boolean, true if current timestamp is within in range (4:10): https://academy.moralis.io/lessons/back-testing-part-1-enabling-datasets-selection
    // v
                            // (year, month, day, hours, mins)
timeInRange = (time > timestamp(fromYear, fromMonth, fromDay, 00, 00)) and (time < timestamp(toYear, toMonth, toDay, 23, 59))

    // v5 added ta.crossover()
// longSignal = ta.crossover(shortMa, longMa) and timeInRange and r < 50
// shortSignal = ta.crossover(longMa, shortMa) and timeInRange and r > 50

//(built-in volume example): (Also, volume over past 5 candles)
longSignal = ta.crossover(shortMa, longMa) and timeInRange and r < 50 and volume > 300
shortSignal = ta.crossover(longMa, shortMa) and timeInRange and r > 50 and volume > 300



// ********************   ENTER POSITIONS  ******************** //
// if longSignal==true 
if longSignal
    // strategy.entry(id="longPosition", strategy.long, 1, comment = "Buy on 20 over 50 SMA cross")
    // strategy.entry("longPosition", strategy.long, 0.1, comment = "Buy on 20 over 50 SMA cross")
    strategy.entry("longPosition", strategy.long, trade_amount, comment = "Buy on 20 over 50 SMA cross")


if shortSignal
    strategy.entry("shortPosition", strategy.short, trade_amount, comment = "shortSignal on 50 over 20 SMA cross")

// When you enter a short position, TradingView automatically closes any open positions you have? (3:40)

